apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: zap-events
  namespace: zapier
  labels:
    strimzi.io/cluster: zapier-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: zap-events-dlq
  namespace: zapier
  labels:
    strimzi.io/cluster: zapier-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824