apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend-deployment
  namespace: zapier
spec:
  replicas: 2
  strategy:
    canary:
      activeService: frontend-active
      canaryService: frontend-canary
      trafficRouting:
        nginx:
          stableIngress: zapier-ingress
      steps:
        - setWeight: 10
          pause: { duration: 2m }
        - setWeight: 30
          pause: { duration: 5m }
        - setWeight: 50
          pause: {} # Pause indefinitely until manually promoted
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ajaygaur0103/frontend:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: frontend-config
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

