version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env

  primarybackend:
    build:
      context: .
      dockerfile: apps/primarybackend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env

  hooks:
    build:
      context: .
      dockerfile: apps/hooks/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  processor:
    build:
      context: .
      dockerfile: apps/processor/Dockerfile
    env_file:
      - .env

  scheduler:
    build:
      context: .
      dockerfile: apps/scheduler/Dockerfile
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    env_file:
      - .env

  notification-service:
    build:
      context: .
      dockerfile: apps/services/Dockerfile
    env_file:
      - .env
