apiVersion: v1
kind: Service
metadata:
  name: notification-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
