apiVersion: v1
kind: Service
metadata:
  name: hooks-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  selector:
    app: hooks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP    
  