apiVersion: apps/v1
kind: Deployment
metadata:
    name: hooks-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: hooks
    template:
        metadata:
            labels:
                app: hooks
        spec:
            containers:
            -   name: hooks
                image: ajaygaur0103/hooks:latest
                envFrom:
                -   configMapRef:
                        name: hooks-config
                -   secretRef:
                        name: hooks-secret
                ports:
                -   containerPort: 8000
                resources:
                    requests:
                        cpu: "100m"
                        memory: "128Mi"
                    limits:
                        cpu: "500m"
                        memory: "512Mi"